app:
  name: cursinhomanager
  description: Cursinho Manager is an API to manage occurrences
  version: 0.0.2

server.port: 8080

# DataSource config
spring:
  datasource:
    url: ${URL}
    username: root
    password: ${SENHA}
    hikari:
      minimumIdle: 10
      maximumPoolSize: 10
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false