app:
  name: cursinhomanager
  description: Cursinho Manager is an API to manage occurrences
  version: 0.0.2

server:
  port: 8080

# DataSource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/informatica?useSSL=false
    username: root
    password: Ernetwork*
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false